name: 'pull-request-vir'
description: 'Handle pull request reviews, assignments, and ability to merge.'
branding:
    icon: 'git-pull-request'
    color: 'blue'
inputs:
    config-file:
        description: 'TypeScript config file'
        required: true
outputs:
    status:
        description: 'The result of the checks'
runs:
    using: 'node20'
    main: 'dist-action/action/run-action.js'
