name: 'pull-request-vir'
description: 'Handle pull request reviews, assignments, and ability to merge.'
branding:
    icon: 'git-pull-request'
    color: 'blue'
inputs:
    config_file:
        description: 'TypeScript config file'
        required: true
    token:
        description: 'Token used to access the repo with'
        default: ${{ github.token }}
outputs:
    status:
        description: 'The result of the checks'
runs:
    using: 'node20'
    main: 'src/action/action-entry-point.js'
