name: 'test-this-action'

on: [push]

permissions:
    contents: write

jobs:
    test-this-action:
        runs-on: ubuntu-latest
        name: Test this action
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: Install node_modules
              run: npm ci
            - name: Run the action
              uses: ./
              id: internal-action
              with:
                  config-file: 'configs/internal-action.config.ts'
            - name: Get the output status
              run: echo "The status was ${{ steps.internal-action.outputs.status }}"
